name: schedule_there
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.5
  url_launcher: ^5.0.2
  image_picker: ^0.6.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/person.png
  